### ISSUE TITLE
about MAP

### ISSUE THREAD

**Issue by JingnanXu97** [idejie/DSAH#1]
Can I ask you for the top-k data of the methods that you've compared with？  I'm sorry for this but I really need it now. Because part of these methods' code I can't find. Thank you very much…

**Comment by idejie** [comment]
Sorry for the late reply. The part (top-k data )have been implemented in [metric.py#L197](https://github.com/idejie/DSAH/blob/b23197650de4f619d21e6613deb6e9abc4cb831f/metric.py#L197)

**Comment by idejie** [comment]
Sorry for the late reply. The part (top-k data )have been implemented in [metric.py#L197](https://github.com/idejie/DSAH/blob/b23197650de4f619d21e6613deb6e9abc4cb831f/metric.py#L197)
